-- TOKAJUDA • BANCO + SEGURANÇA
-- Execute este arquivo no Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  username text not null check (char_length(username) between 2 and 60),
  referral_url text not null check (char_length(referral_url) between 10 and 1000),
  proof_path text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  approved_at timestamptz
);

create table if not exists public.clicks (
  id bigint generated by default as identity primary key,
  submission_id uuid not null references public.submissions(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.submissions enable row level security;
alter table public.clicks enable row level security;
alter table public.admins enable row level security;

-- Público: pode criar uma nova solicitação, mas não escolher status.
drop policy if exists "public_submit_pending" on public.submissions;
create policy "public_submit_pending"
on public.submissions for insert
to anon, authenticated
with check (status = 'pending' and approved_at is null);

-- Público: só enxerga registros aprovados.
drop policy if exists "public_read_approved" on public.submissions;
create policy "public_read_approved"
on public.submissions for select
to anon, authenticated
using (
  status = 'approved'
  or exists (select 1 from public.admins a where a.user_id = auth.uid())
);

-- Admin: pode atualizar e excluir.
drop policy if exists "admin_update_submissions" on public.submissions;
create policy "admin_update_submissions"
on public.submissions for update
to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admin_delete_submissions" on public.submissions;
create policy "admin_delete_submissions"
on public.submissions for delete
to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

-- Cliques: qualquer visitante pode registrar um clique.
drop policy if exists "public_insert_clicks" on public.clicks;
create policy "public_insert_clicks"
on public.clicks for insert
to anon, authenticated
with check (
  exists (
    select 1 from public.submissions s
    where s.id = submission_id and s.status = 'approved'
  )
);

-- Contagem pública.
drop policy if exists "public_read_clicks" on public.clicks;
create policy "public_read_clicks"
on public.clicks for select
to anon, authenticated
using (true);

-- Cada usuário autenticado só consegue confirmar se ELE é admin.
drop policy if exists "admin_self_read" on public.admins;
create policy "admin_self_read"
on public.admins for select
to authenticated
using (user_id = auth.uid());

-- STORAGE
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'proofs',
  'proofs',
  false,
  5242880,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public = false,
  file_size_limit = 5242880,
  allowed_mime_types = array['image/jpeg','image/png','image/webp'];

-- Visitante pode enviar arquivos apenas para public/
drop policy if exists "anon_upload_proofs" on storage.objects;
create policy "anon_upload_proofs"
on storage.objects for insert
to anon, authenticated
with check (
  bucket_id = 'proofs'
  and (storage.foldername(name))[1] = 'public'
);

-- Apenas admin pode visualizar prints.
drop policy if exists "admin_read_proofs" on storage.objects;
create policy "admin_read_proofs"
on storage.objects for select
to authenticated
using (
  bucket_id = 'proofs'
  and exists (select 1 from public.admins a where a.user_id = auth.uid())
);

-- Apenas admin pode apagar prints.
drop policy if exists "admin_delete_proofs" on storage.objects;
create policy "admin_delete_proofs"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'proofs'
  and exists (select 1 from public.admins a where a.user_id = auth.uid())
);

-- IMPORTANTE:
-- 1. Em Authentication > Users, crie seu usuário administrador.
-- 2. Copie o UUID dele.
-- 3. Rode:
-- insert into public.admins (user_id) values ('COLE-O-UUID-DO-ADMIN-AQUI');
